spring.application.name=rentron

spring.datasource.url=jdbc:mysql://209.182.233.156:4081/appdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=appuser
spring.datasource.password=G82yeByi35"I

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false

core.fileTransfer.primaryUploadFolder=/opt/microservice/upload/images

# Multipart file upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
